[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
chrono = "0.4.38"
config = "0.14.0"
env_logger = "0.11.5"
serde = "1.0.210"
surrealdb = "1.5.5"
thiserror = "1.0.63"
tokio = "1.40.0"
